// Auto-generated by the postman-to-k6 converter

import "./libs/shim/core.js";

export let options = { maxRedirects: 4 };

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options
});

export default function() {
  postman[Request]({
    name: "create and start trip",
    id: "743ab36f-ff58-4de8-bcc6-f2e0b1a6a524",
    method: "POST",
    address: "https://prod-tracking.saudabooks.com/v1/trip/createAndStart",
    data:
      '{\n    "source_address": {\n        "lat": "26.0905486",\n        "long": "85.4616572",\n        "default_name": "Manika math",\n        "detailed_address": "Manika math bihar",\n        "district": "MANIKA",\n        "pincode": 843148,\n        "state": "Bihar"\n    },\n    "destination_address": {\n        "lat": "26.289080",\n        "long": "84.4592701",\n        "default_name": "Mira chapra madhaupur",\n        "detailed_address": "As feeds , Mira chapra madhaupur , Siwan Bihar",\n        "district": "Siwan",\n        "pincode": 841232,\n        "state": "Bihar"\n    },\n    "name": "Namd kumar singh ",\n    "additional_info":{\n        "vehicle_number":"Up56AT2072"\n    },\n    "mobile_number_for_tracking": "8294913792"\n}',
    headers: {
      "Content-Type": "application/json",
      Authorization:
        "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbmNyeXB0ZWRfdG9rZW4iOiJkMzA1NjM2YTk0YmFlNmFmNzY3OGQ3YzljMjc3IiwiaWF0IjoxNzA5NzA4NzczfQ.TCBfwKvhLPDo2wpOahe_sxc_Pjqy_qOMS6BSGV9onos",
      apikey:
        "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbmNyeXB0ZWRfdG9rZW4iOiI3MDVmZjZkZTEyY2NmYTViOTljYjMxMmM4MzE2OTM3ODhmIiwiaWF0IjoxNzEyNTYwODMxfQ.mYuh_QQyXB8ZTAZoXQhYWK2h51GCZXBYb6ycnuiK2oo"
    }
  });

  postman[Request]({
    name: "External Trip Details",
    id: "0b8c0e26-77c2-4e1f-9d77-9171ca551366",
    method: "GET",
    address:
      "https://dev-tracking.saudabooks.com/v2/trip/tripDetailExternal?encrypted_trip_id=90427528c2ab8bf0773cdf",
    headers: {
      apiKey:
        "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbmNyeXB0ZWRfdG9rZW4iOiJkMzA1NjY3NTkwYmNkZmE5NjAzN2IyOTk5MDI4YzZmMzIyIiwiaWF0IjoxNzA3OTAxNzk5fQ.R2Qv1TPHAf1wjt4K8VOdZ9tHsZgMc4GgZ_VogN_HUiA"
    }
  });

  postman[Request]({
    name: "Change Number For tracking",
    id: "b4f0e8c5-77b4-47d7-a71b-c88d079c8c28",
    method: "PATCH",
    address: "https://prod-tracking.saudabooks.com/v1/trip/editMobileNumber",
    data: {
      encrypted_trip_id:
        "d305727082b8d8b27132b283816791a32d26ec27511140c05b2e1a53f2c40167b1d8dc57b5f488e4d461f2ab790fb21b0bb0f328994793ada65367cf0beec3",
      trip_number: "TRPFM24012648",
      mobile_number_for_tracking: "9352025660"
    },
    headers: {
      apikey:
        "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbmNyeXB0ZWRfdG9rZW4iOiI3MDVmZjZkZTEyY2NmYTViOTljYjMxMmM4MzE2OTM3ODhmIiwiaWF0IjoxNzEyNTYwODMxfQ.mYuh_QQyXB8ZTAZoXQhYWK2h51GCZXBYb6ycnuiK2oo"
    }
  });

  postman[Request]({
    name: "get_platform_api_key",
    id: "7a23a809-20ad-4ea4-9cea-76b661bc106b",
    method: "POST",
    address: "https://dev-tracking.saudabooks.com/v1/auth/getApiKey",
    data: {
      encrypted_token:
        "CYVRHQfYYrcScZJZDEIrdj4hGJnM5i0Zb2qiFOGhUbsNAFrwwLVidtIvTOy8R9yId/senQ40dnm4Zf9qL9g1gMn9cqCCWgRbTLSExIY5vxv7+vFO7qLbTIa9NlSemWvp2Elaz6RmScU6tjIeveTxDZvwICol4yFI16i/bnElJ/N8mVBZ2cp31BIWzzs9/NJwJ1/DfQSicOpQgedZUxV+6zg4OEeJ/0s/NoBNLGvJ9AgxjDEFFBYIJsG5rSq2MSGJ7wfdeQx2NWtx7sWht//jCAuVr0NjRZ5i3yGvrgB+2S9HILI7tI+9Kvapng/wlz6oVb+Bvo5OD/KYB51Kz09tHQ==",
      email_id: "neeraj1@farmart.co"
    },
    headers: {
      "Content-Type": "application/x-www-form-urlencoded"
    }
  });

  postman[Request]({
    name: "Fetch Location List",
    id: "e917cbe8-5466-4def-801f-54b6fcb4945b",
    method: "GET",
    address:
      "https://dev-tracking.saudabooks.com/v1/trip/tripDetailExternal?encrypted_trip_id=90427528c2ab8bf0773cdf"
  });

  postman[Request]({
    name: "edit locatiojn",
    id: "61c3a1a7-afb8-4001-95f7-89219d83a992",
    method: "PATCH",
    address: "https://dev-tracking.saudabooks.com/v1/trip/editTripAddress",
    data:
      '{\n    "trip_number":"TRPSB24000554",\n    "source_address": {\n        "lat": "28.5118907",\n        "long": "77.0861871",\n        "default_name": "Aihp 2",\n        "detailed_address": "Aihp 2",\n        "district": "Gurugram",\n        "pincode": null,\n        "state": ""\n    },\n    "destination_address": {\n        "lat": "28.5118514",\n        "long": "77.0697161",\n        "default_name": "Hanuman Chawk 2",\n        "detailed_address": "Hanuman Chawk 2",\n        "district": "Gurugram",\n        "pincode": null,\n        "state": ""\n    }\n}',
    headers: {
      "Content-Type": "application/json",
      apikey:
        "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbmNyeXB0ZWRfdG9rZW4iOiJkMzA1NjY3NTkwYmNkZmE5NjAzN2IyOTk5MDI4YzZmNzIyIiwiaWF0IjoxNzEwNzQ3MzExfQ.sQb0my8ooNMfqOt9o77iYWjgiILuTwHN1kHlsZZI0zo"
    }
  });

  postman[Request]({
    name: "fetch Trip Details",
    id: "9cba1e0e-9e89-4b94-9ae9-2d730feb64c4",
    method: "GET",
    address:
      "https://dev-tracking.saudabooks.com/v2/trip/tripDetailExternal?encrypted_trip_id=90427528c2ab8bf0773cdf"
  });

  postman[Request]({
    name: "Refresh Consent Status",
    id: "60ffdc91-91ef-4076-b695-7b84c458e22a",
    method: "POST",
    address: "https://dev-tracking.saudabooks.com/v1/trip/refreshConsent",
    data: {
      mobile_number: "",
      trip_number: "TRPFM24001056"
    },
    headers: {
      apikey:
        "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbmNyeXB0ZWRfdG9rZW4iOiJkMzA1NjY3NTkwYmNkZmE5NjAzN2IyOTk5MDI4YzZmNzIyIiwiaWF0IjoxNzEwNzQ3MzExfQ.sQb0my8ooNMfqOt9o77iYWjgiILuTwHN1kHlsZZI0zo",
      "Content-Type": "application/x-www-form-urlencoded"
    }
  });
}
