name: K6 Load Testing

on:  
  push:  
    branches: [ main ]  
  pull_request:  
    branches: [ main ]  

jobs:  
  load-test:  
    runs-on: ubuntu-latest  
    steps:  
      - name: Checkout Repository  
        uses: actions/checkout@v2  

      - name: Install K6  
        run: sudo apt-get install -y k6  

      - name: Run Load Test  
        run: k6 run tests/load_test.js  
